<?
$PERM["blog"]["7"]="W";
$PERM["news"]["6"]="W";
$PERM["news"]["7"]="W";
$PERM["personal"]["6"]="W";
$PERM["personal"]["7"]="W";
$PERM["catalog"]["6"]="W";
$PERM["catalog"]["7"]="W";
$PERM["about"]["6"]="W";
$PERM["about"]["7"]="W";
$PERM["/"]["*"]="R";
$PERM["desktop_app"]["*"]="D";
$PERM["online"]["*"]="R";
$PERM["actions"]["*"]="R";
$PERM["upload"]["8"]="T_8";
$PERM["index.php"]["7"]="W";
$PERM["custom-scripts"]["*"]="D";
$PERM["custom-scripts"]["8"]="W";
$PERM["custom-scripts"]["6"]="W";
?>