<?
$PERM["desktop_app"]["*"]="D";
$PERM["/"]["*"]="R";
$PERM["online"]["*"]="R";
$PERM["actions"]["*"]="R";
$PERM["upload"]["8"]="T_8";
$PERM["personal"]["7"]="W";
$PERM["catalog"]["7"]="W";
$PERM["news"]["7"]="W";
$PERM["about"]["7"]="W";
$PERM["index.php"]["7"]="W";
?>