<?
$aMenuLinks = Array(
	Array(
		"Где купить", 
		"https://www.alpinabook.ru/content/whereToBuy/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Мероприятия", 
		"https://www.alpinabook.ru/events/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Контакты", 
		"https://www.alpinabook.ru/about/contacts/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Авторам", 
		"https://www.alpinabook.ru/content/publisher/authors/", 
		Array(), 
		Array(), 
		"" 
	)
);
?>