<?
$aMenuLinks = Array(
    Array(
        "Оплата", 
        "https://www.alpinabook.ru/content/payment/", 
        Array(), 
        Array(), 
        "" 
    ),
    Array(
        "Доставка", 
        "https://www.alpinabook.ru/content/delivery/", 
        Array(), 
        Array(), 
        "" 
    ),
    Array(
        "Скидки", 
        "https://www.alpinabook.ru/content/discounts/", 
        Array(), 
        Array(), 
        "" 
    ),
    Array(
        "Где мой заказ?", 
        "https://www.alpinabook.ru/content/where-order-content/", 
        Array(), 
        Array(), 
        "" 
    ),
    Array(
        "Контакты", 
        "https://www.alpinabook.ru/about/contacts/", 
        Array(), 
        Array(), 
        "" 
    )
);
?>