<?
$aMenuLinks = Array(
    Array(
        "Оплата", 
        "/content/payment/", 
        Array(), 
        Array(), 
        "" 
    ),
    Array(
        "Доставка", 
        "/content/delivery/", 
        Array(), 
        Array(), 
        "" 
    ),
    Array(
        "Скидки", 
        "/content/discounts/", 
        Array(), 
        Array(), 
        "" 
    ),
    Array(
        "Где мой заказ?", 
        "/content/where-order-content/", 
        Array(), 
        Array(), 
        "" 
    ),
    Array(
        "Контакты", 
        "/about/contacts/", 
        Array(), 
        Array(), 
        "" 
    )
);
?>