<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Заказы");
?><?$APPLICATION->IncludeComponent(
    "bitrix:sale.order.ajax",
    "",
    array(
        "PAY_FROM_ACCOUNT" => "N",
        "COUNT_DELIVERY_TAX" => "N",
        "COUNT_DISCOUNT_4_ALL_QUANTITY" => "N",
        "ONLY_FULL_PAY_FROM_ACCOUNT" => "N",
        "ALLOW_AUTO_REGISTER" => "Y",
        "SEND_NEW_USER_NOTIFY" => "Y",
        "DELIVERY_NO_AJAX" => "N",
        "TEMPLATE_LOCATION" => ".default",
        "PROP_1" => "",
        "PATH_TO_BASKET" => "/personal/cart/",
        "PATH_TO_PERSONAL" => "/personal/order/",
        "PATH_TO_PAYMENT" => "/personal/order/payment/",
        "PATH_TO_ORDER" => "/personal/order/make/",
        "SET_TITLE" => "Y",
        "DELIVERY2PAY_SYSTEM" => "",
        "SHOW_ACCOUNT_NUMBER" => "Y",
        "DELIVERY_NO_SESSION" => "Y",
        "COMPONENT_TEMPLATE" => "order",
        "DELIVERY_TO_PAYSYSTEM" => "d2p",
        "USE_PREPAYMENT" => "Y",
        "PROP_2" => "",
        "ALLOW_NEW_PROFILE" => "Y",
        "SHOW_PAYMENT_SERVICES_NAMES" => "Y",
        "SHOW_STORES_IMAGES" => "N",
        "PATH_TO_AUTH" => "/auth/",
        "DISABLE_BASKET_REDIRECT" => "N",
        "PRODUCT_COLUMNS" => "",
        "COMPATIBLE_MODE" => "Y",
        "BASKET_IMAGES_SCALING" => "adaptive",
        "ALLOW_USER_PROFILES" => "Y",
        "TEMPLATE_THEME" => "site",
        "SHOW_PAY_SYSTEM_LIST_NAMES" => "Y",
        "SHOW_PAY_SYSTEM_INFO_NAME" => "Y",
        "SHOW_DELIVERY_PARENT_NAMES" => "Y",
        "BASKET_POSITION" => "after",
        "SHOW_BASKET_HEADERS" => "N",
        "DELIVERY_FADE_EXTRA_SERVICES" => "N",
        "SHOW_COUPONS_BASKET" => "Y",
        "SHOW_COUPONS_DELIVERY" => "Y",
        "SHOW_COUPONS_PAY_SYSTEM" => "Y",
        "SHOW_NEAREST_PICKUP" => "N",
        "DELIVERIES_PER_PAGE" => "8",
        "PAY_SYSTEMS_PER_PAGE" => "8",
        "PICKUPS_PER_PAGE" => "5",
        "SHOW_MAP_IN_PROPS" => "N",
        "PROPS_FADE_LIST_1" => "",
        "PROPS_FADE_LIST_2" => "",
        "PRODUCT_COLUMNS_VISIBLE" => array(
            0 => "PREVIEW_PICTURE",
            1 => "PROPS",
        ),
        "PRODUCT_COLUMNS_HIDDEN" => "",
        "USE_CUSTOM_MAIN_MESSAGES" => "N",
        "USE_CUSTOM_ADDITIONAL_MESSAGES" => "N",
        "USE_CUSTOM_ERROR_MESSAGES" => "N",
        "ADDITIONAL_PICT_PROP_4" => "-",
        "SHOW_TOTAL_ORDER_BUTTON" => "Y",
        "SHOW_DELIVERY_LIST_NAMES" => "Y",
        "SHOW_DELIVERY_INFO_NAME" => "Y",
        "USE_YM_GOALS" => "N",
        "SHOW_ORDER_BUTTON" => "final_step",
        "SKIP_USELESS_BLOCK" => "Y",
        "SERVICES_IMAGES_SCALING" => "standard",
        "SHOW_NOT_CALCULATED_DELIVERIES" => "L",
        "USE_PRELOAD" => "Y",
        "ACTION_VARIABLE" => "action",
        "ADDITIONAL_PICT_PROP_66" => "-",
        "COMPOSITE_FRAME_MODE" => "A",
        "COMPOSITE_FRAME_TYPE" => "AUTO",
        "USE_ENHANCED_ECOMMERCE" => "N"
    ),
    false
);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>