<?require_once($_SERVER['DOCUMENT_ROOT']."/bitrix/modules/main/include/prolog_before.php");
    /*if(empty($_SESSION['price_delivery']) || $_SESSION['cyty'] != $_REQUEST["city"]){
		
        $url='http://api.boxberry.de/json.php?token='.BOXBERRY_TOKEN.'&method=ListZips';

        $handle = fopen($url, "rb");
        $contents = stream_get_contents($handle);
        fclose($handle);
        $array = json_decode($contents, true);


        foreach($array as $city){
            if($city["City"] == $_REQUEST["city"]){
                $ar_param_city = $city;
            }
        }

        $url_zip='http://api.boxberry.de/json.php?token='.BOXBERRY_TOKEN.'&method=DeliveryCosts&weight=1&zip='.$ar_param_city["Zip"];

        $handle_zip = fopen($url_zip, "rb");
        $content = stream_get_contents($handle_zip);
        fclose($handle_zip);

        $array_pvz = json_decode($content, true);

        if($array_pvz["price"] > 0){
            session_start();
            $_SESSION['price_delivery'] = round($array_pvz["price"]);
            $_SESSION['cyty'] = $_REQUEST["city"];
        }
        echo round($array_pvz["price"]);
    }*/
	
	
$cities = array(
	array('Ангарск', 1129),
	array('Петропавловск-Камчатский', 964),
	array('Южно-Сахалинск', 964),
	array('Якутск', 964),
	array('Лосино-Петровский', 942),
	array('Ногинск', 942),
	array('Электросталь', 942),
	array('Ясный', 912),
	array('Электроугли', 862),
	array('Гатчина', 787),
	array('Кувандык', 752),
	array('Медногорск', 752),
	array('Шелехов', 700),
	array('Гай', 672),
	array('Новотроицк', 672),
	array('Асбест', 645),
	array('Белоярский', 645),
	array('Заречный', 645),
	array('Заречный', 645),
	array('Дзержинск', 640),
	array('Бирюч', 627),
	array('Валуйки', 627),
	array('Грайворон', 627),
	array('Коммунар', 627),
	array('Златоуст', 592),
	array('Ревда', 592),
	array('Троицк', 592),
	array('Чебаркуль', 592),
	array('Первоуральск', 565),
	array('Шебекино', 556),
	array('Северск', 555),
	array('Снежинск', 555),
	array('Никольское', 554),
	array('Алексеевка', 547),
	array('Короча', 547),
	array('Нововоронеж', 547),
	array('Новый Оскол', 547),
	array('Отрадное', 547),
	array('Павловск', 547),
	array('Семилуки', 547),
	array('Строитель', 547),
	array('Арамиль', 505),
	array('Верхняя Пышма', 505),
	array('Копейск', 505),
	array('Среднеуральск', 505),
	array('Михайловск', 496),
	array('Михайловск', 496),
	array('Нерехта', 496),
	array('Новочеркасск', 496),
	array('Сертолово', 496),
	array('Всеволожск', 487),
	array('Курчатов', 487),
	array('Ачинск', 460),
	array('Бийск', 460),
	array('Биробиджан', 460),
	array('Благовещенск', 460),
	array('Благовещенск', 460),
	array('Братск', 460),
	array('Владивосток', 460),
	array('Иркутск', 460),
	array('Карпинск', 460),
	array('Комсомольск-на-Амуре', 460),
	array('Нижневартовск', 460),
	array('Ноябрьск', 460),
	array('Североуральск', 460),
	array('Сургут', 460),
	array('Улан-Удэ', 460),
	array('Хабаровск', 460),
	array('Ханты-Мансийск', 460),
	array('Чита', 460),
	array('Инкерман', 425),
	array('Севастополь', 425),
	array('Балашиха', 402),
	array('Балашов', 402),
	array('Верея', 402),
	array('Видное', 402),
	array('Вольск', 402),
	array('Дедовск', 402),
	array('Дзержинский', 402),
	array('Долгопрудный', 402),
	array('Домодедово', 402),
	array('Жуковский', 402),
	array('Ивантеевка', 402),
	array('Котельники', 402),
	array('Красногорск', 402),
	array('Лобня', 402),
	array('Лыткарино', 402),
	array('Люберцы', 402),
	array('Мытищи', 402),
	array('Одинцово', 402),
	array('Подольск', 402),
	array('Пушкино', 402),
	array('Раменское', 402),
	array('Реутов', 402),
	array('Родники', 402),
	array('Старая Купавна', 402),
	array('Химки', 402),
	array('Абакан', 375),
	array('Архангельск', 375),
	array('Балаково', 375),
	array('Барнаул', 375),
	array('Верхняя Тура', 375),
	array('Воркута', 375),
	array('Евпатория', 375),
	array('Каменск-Уральский', 375),
	array('Качканар', 375),
	array('Кемерово', 375),
	array('Краснотурьинск', 375),
	array('Красноуральск', 375),
	array('Красноярск', 375),
	array('Кушва', 375),
	array('Лесной', 375),
	array('Маркс', 375),
	array('Невинномысск', 375),
	array('Нижний Тагил', 375),
	array('Нижняя Тура', 375),
	array('Новокузнецк', 375),
	array('Новосибирск', 375),
	array('Новоуральск', 375),
	array('Рубцовск', 375),
	array('Северодвинск', 375),
	array('Серов', 375),
	array('Симферополь', 375),
	array('Томск', 375),
	array('Туймазы', 375),
	array('Ухта', 375),
	array('Энгельс', 375),
	array('Азов', 366),
	array('Батайск', 366),
	array('Тольятти', 366),
	array('Владимир', 357),
	array('Майский', 357),
	array('Альметьевск', 352),
	array('Армавир', 352),
	array('Белебей', 352),
	array('Березники', 352),
	array('Бузулук', 352),
	array('Волгодонск', 352),
	array('Ейск', 352),
	array('Ишимбай', 352),
	array('Калининград', 352),
	array('Кузнецк', 352),
	array('Махачкала', 352),
	array('Миасс', 352),
	array('Мурманск', 352),
	array('Октябрьский', 352),
	array('Омск', 352),
	array('Орск', 352),
	array('Салават', 352),
	array('Соликамск', 352),
	array('Стерлитамак', 352),
	array('Тобольск', 352),
	array('Шадринск', 352),
	array('Владикавказ', 325),
	array('Димитровград', 325),
	array('Екатеринбург', 325),
	array('Ижевск', 325),
	array('Киров', 325),
	array('Киров', 325),
	array('Курган', 325),
	array('Магнитогорск', 325),
	array('Нальчик', 325),
	array('Нижнекамск', 325),
	array('Новокуйбышевск', 325),
	array('Оренбург', 325),
	array('Пермь', 325),
	array('Петрозаводск', 325),
	array('Рузаевка', 325),
	array('Саранск', 325),
	array('Саратов', 325),
	array('Сыктывкар', 325),
	array('Тюмень', 325),
	array('Челябинск', 325),
	array('Шахты', 325),
	array('Шумиха', 325),
	array('Элиста', 325),
	array('Астрахань', 316),
	array('Волгоград', 316),
	array('Волжский', 316),
	array('Вологда', 316),
	array('Дятьково', 316),
	array('Изобильный', 316),
	array('Казань', 316),
	array('Камышин', 316),
	array('Ковров', 316),
	array('Коломна', 316),
	array('Кострома', 316),
	array('Краснодар', 316),
	array('Майкоп', 316),
	array('Набережные Челны', 316),
	array('Новороссийск', 316),
	array('Павлово', 316),
	array('Пенза', 316),
	array('Пятигорск', 316),
	array('Ростов-на-Дону', 316),
	array('Рыбинск', 316),
	array('Самара', 316),
	array('Смоленск', 316),
	array('Ставрополь', 316),
	array('Старый Оскол', 316),
	array('Сызрань', 316),
	array('Таганрог', 316),
	array('Ульяновск', 316),
	array('Уфа', 316),
	array('Белгород', 307),
	array('Брянск', 307),
	array('Великий Новгород', 307),
	array('Воронеж', 307),
	array('Выборг', 307),
	array('Иваново', 307),
	array('Йошкар-Ола', 307),
	array('Калуга', 307),
	array('Курск', 307),
	array('Липецк', 307),
	array('Наро-Фоминск', 307),
	array('Нижний Новгород', 307),
	array('Псков', 307),
	array('Рязань', 307),
	array('Тамбов', 307),
	array('Тверь', 307),
	array('Тула', 307),
	array('Чебоксары', 307),
	array('Череповец', 307),
	array('Ярославль', 307),
	array('Санкт-Петербург', 247),
	array('Москва', 222),
);

	$setPrice = false;
	
	foreach($cities as $city) {
		if($city[0] == $_REQUEST["city"]){
			echo $city[1];
			$setPrice = true;
		}
	}
	if (!$setPrice)
		echo 319;

?>