    <table cellspacing="5" cellpadding="5" border="0" width="100&#37;">      
      <tbody> 
        <tr>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;">             <dl>                 <dt><strong><u><b>Год 2009 </b></u></strong>                 </dt></dl>         </td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;"></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;"></td>     </tr>
         
        <tr>         <td height="67" style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;"></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;"></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;">             <dl>                 <dt><strong>Конференция &laquo;Предпринимательство и новые                 технологии России 2009&raquo;</strong></dt><dt>                 Благодарность за информационную поддержку.</dt></dl>         </td>     </tr>
         
        <tr>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;"></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;"></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;">             <dl>                 <dt><strong>Российская ассоциация Бизнес-Образования</strong></dt><dt>                 Свидетельство о вступлении издательства в организацию.</dt></dl>         </td>     </tr>
         
        <tr>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;">             <a onclick="javascript:window.open('/images/nagradi/11.jpg','big','top=15, left=20, menubar=0, toolbar=0, location=0, directories=0, status=0, scrollbars=0, resizable=1, width=300, height=450');" href="javascript://"><img border="0" align="RIGHT" name="Графический объект11" src="/images/nagradi/11s.jpg" /></a></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;"></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;">             <dl>                 <dt><strong><b>Красноярская ярмарка книжной культуры</b></strong></dt><dt>                 Диплом за участие и вклад в развитие книжного дела в Сибири</dt></dl>         </td>     </tr>
         
        <tr>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;">             <a onclick="javascript:window.open('/images/nagradi/06.jpg','big','top=15, left=20, menubar=0, toolbar=0, location=0, directories=0, status=0, scrollbars=0, resizable=1, width=300, height=450');" href="javascript://"><img border="0" align="RIGHT" name="Графический объект11" src="/images/nagradi/06s.jpg" /></a></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;"></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;">             <dl>                 <dt><strong><span lang="en-US"><b>IX </b></span></strong><strong><span lang="ru-RU"><b>ежегодная                 выставки и конференции </b></span></strong><strong><span lang="en-US"><b>Trainings                 expo 2009</b></span></strong></dt><dt>                 Сертификат участника, благодарность за экспертный вклад в                 развитие рынка обучения персонала, за открытость и готовность                 делиться опытом и инновационными решениями</dt></dl>         </td>     </tr>
         
        <tr>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;">             <dl>                 <dt><strong><u><b>Год 2007</b></u></strong></dt></dl>         </td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;"></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;"></td>     </tr>
         
        <tr>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;">             <a onclick="javascript:window.open('/images/news/economics.gif','big','top=15, left=20, menubar=0, toolbar=0, location=0, directories=0, status=0, scrollbars=0, resizable=1, width=300, height=450');" href="javascript://"><img border="0" align="RIGHT" name="Графический объект11" src="/images/news/economics_mini.gif" /></a></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;"></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;">             <dl>                 <dt><strong>Экономик' с</strong></dt><dt>                 Диплом за многолетнее партнерство и дружбу.</dt></dl>         </td>     </tr>
         
        <tr>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;">             <a onclick="javascript:window.open('/images/news/kapitan rossiyskogo biznesa.gif','big','top=15, left=20, menubar=0, toolbar=0, location=0, directories=0, status=0, scrollbars=0, resizable=1, width=300, height=450');" href="javascript://"><img border="0" align="RIGHT" name="Графический объект11" src="/images/news/kapitan&#37;20rossiyskogo&#37;20biznesa_mini.gif" /></a></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;"></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;">             <dl>                 <dt><strong>Национальная Деловая Премия &laquo;Капитаны                 Российского бизнеса&raquo;</strong></dt><dt>                 Диплом в номинации Деловые книги.</dt></dl>         </td>     </tr>
         
        <tr>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;">             <a onclick="javascript:window.open('/images/news/moll&#37;202007.gif','big','top=15, left=20, menubar=0, toolbar=0, location=0, directories=0, status=0, scrollbars=0, resizable=1, width=300, height=450');" href="javascript://"><img border="0" align="RIGHT" name="Графический объект11" src="/images/news/moll&#37;202007_mini.gif" /></a></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;"></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;">             <dl>                 <dt><strong>Международная выставка &laquo;МОЛЛ 2007&raquo;</strong></dt><dt>                 Благодарность за информационную поддержку.</dt></dl>         </td>     </tr>
         
        <tr>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;">             <a onclick="javascript:window.open('/images/nagradi/08.jpg','big','top=15, left=20, menubar=0, toolbar=0, location=0, directories=0, status=0, scrollbars=0, resizable=1, width=300, height=450');" href="javascript://"><img border="0" align="RIGHT" name="Графический объект11" src="/images/nagradi/08s.jpg" /></a></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;"></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;">             <dl>                 <dt><strong><b>Конкурса &laquo;Лучшие книги года&raquo; АСКИ </b></strong>                 </dt><dt>                 Диплом за книгу Дж.Лайкера &laquo;<a href="http://www.alpinabook.ru/catalogue/4208.html" target="_blank">Дао Toyota: 14 принципов менеджмента ведущей компании мира</a>&raquo;.</dt></dl>         </td>     </tr>
         
        <tr>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;">             <a onclick="javascript:window.open('/images/nagradi/02.jpg','big','top=15, left=20, menubar=0, toolbar=0, location=0, directories=0, status=0, scrollbars=0, resizable=1, width=300, height=450');" href="javascript://"><img border="0" align="RIGHT" name="Графический объект11" src="/images/nagradi/02s.jpg" /></a></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;"></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;">             <dl>                 <dt><strong><span lang="en-US"><b>V </b></span></strong><strong><span lang="ru-RU"><b>Международная                 книжная и полиграфическая ярмарка &laquo;По великому шелковому                 пути&raquo; (Казахстан)</b></span></strong></dt><dt>                 Диплом за активное участие</dt></dl>         </td>     </tr>
         
        <tr>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;">             <a onclick="javascript:window.open('/images/nagradi/03.jpg','big','top=15, left=20, menubar=0, toolbar=0, location=0, directories=0, status=0, scrollbars=0, resizable=1, width=300, height=450');" href="javascript://"><img border="0" align="RIGHT" name="Графический объект11" src="/images/nagradi/03s.jpg" /></a></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;"></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;">             <dl>                 <dt><strong><b>Грамота Московского Дома Книги</b></strong></dt><dt>                 За особый вклад в развитие <a target="_blank" href="http://www.alpinabook.ru/">книжной</a> отрасли, активное                 сотрудничество м МДК, а также в связи с 40-летием основания                 Московского Дома Книги на Новом Арбате</dt></dl>         </td>     </tr>
         
        <tr>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;">             <a onclick="javascript:window.open('/images/nagradi/10.jpg','big','top=15, left=20, menubar=0, toolbar=0, location=0, directories=0, status=0, scrollbars=0, resizable=1, width=300, height=450');" href="javascript://"><img border="0" align="RIGHT" name="Графический объект11" src="/images/nagradi/10s.jpg" /></a></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;"></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;">             <dl>                 <dt><strong>Премия журнала &laquo;Свой бизнес&raquo;</strong></dt><dt>                 Диплом лауреата присужден книге Д. Коллинза и У.Лазье &laquo;Больше                 чем бизнес&raquo;.</dt></dl>         </td>     </tr>
         
        <tr>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;">             <dl>                 <dt><u><b>Год 2006 </b></u>                 </dt></dl>         </td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;"></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;"></td>     </tr>
         
        <tr>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;"></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;"></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;">             <dl>                 <dt><b>Национальный Союз Кадровиков</b></dt><dt>                 Диплом участника 3 выставки и конференции Кадровая служба &mdash;                 2006 : Информационное обеспечение.</dt></dl>         </td>     </tr>
         
        <tr>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;">             <a onclick="javascript:window.open('/images/nagradi/09.jpg','big','top=15, left=20, menubar=0, toolbar=0, location=0, directories=0, status=0, scrollbars=0, resizable=1, width=300, height=450');" href="javascript://"><img border="0" align="RIGHT" name="Графический объект11" src="/images/nagradi/09s.jpg" /></a></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;"></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;">             <dl>                 <dt><b>Театрально-поэтический фестиваль &laquo;Булгаковская                 осень&raquo; союза писателей Москвы</b></dt><dt>                 Золотой диплом о присуждении премии &laquo;лучшее издательство                 2006 года&raquo; в номинации &laquo;деловая и экономическая                 литература&raquo;</dt></dl>         </td>     </tr>
         
        <tr>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;">             <a onclick="javascript:window.open('/images/nagradi/12.jpg','big','top=15, left=20, menubar=0, toolbar=0, location=0, directories=0, status=0, scrollbars=0, resizable=1, width=300, height=450');" href="javascript://"><img border="0" align="RIGHT" name="Графический объект11" src="/images/nagradi/12s.jpg" /></a></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;"></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;">             <dl>                 <dt><b>Премия журнала &laquo;Свой бизнес&raquo; Бизнес-книга 2006</b></dt><dt>                 Специальный диплом присужден Манфреду Кетс да Еврису, Станиславу                 Шекшне, Константину Коротову, Элизабет Флорент-Трейси и                 издательству за книгу &laquo;Новые лидеры российского бизнеса&raquo;                 в номинации &laquo;Лучшие книги для предпринимателей&raquo;</dt></dl>         </td>     </tr>
         
        <tr>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;">              
            <p><u><b>Год 2005</b></u></p>
           </td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;"></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;"></td>     </tr>
         
        <tr>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;"></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;"></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;">             <dl>                 <dt><b>Премия журнала &laquo;Маркетинг pro&raquo;</b></dt><dt>                 Диплом победителя конкурса в номинации &laquo;<a target="_blank" href="http://www.alpinabook.ru/MarketingAdvertisingPR/">Лучшие книги о                 маркетинге</a>&raquo;.</dt></dl>         </td>     </tr>
         
        <tr>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;">             <a onclick="javascript:window.open('/images/nagradi/07.jpg','big','top=15, left=20, menubar=0, toolbar=0, location=0, directories=0, status=0, scrollbars=0, resizable=1, width=300, height=450');" href="javascript://"><img border="0" align="RIGHT" name="Графический объект11" src="/images/nagradi/07s.jpg" /></a></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;"></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;">             <dl>                 <dt><b>Всероссийский кадровый конгресс национального союза                 кадровиков</b></dt><dt>                 сертификат участника выставки и конференции &laquo;Кадровая                 служба &mdash; 2005: информационное обеспечение&raquo;</dt></dl>         </td>     </tr>
         
        <tr>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;"></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;"></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;">             <dl>                 <dt><b>Конференция &laquo;Тренинг &mdash; 2005&raquo;</b></dt><dt>                 Диплом участника выставки-конференции.</dt></dl>         </td>     </tr>
         
        <tr>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;">             <dl>                 <dt><u><b>Год 2004 </b></u>                 </dt></dl>         </td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;"></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;"></td>     </tr>
         
        <tr>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;">             <a onclick="javascript:window.open('/images/news/letopis&#37;20magazina&#37;20120.gif','big','top=15, left=20, menubar=0, toolbar=0, location=0, directories=0, status=0, scrollbars=0, resizable=1, width=300, height=450');" href="javascript://"><img border="0" align="RIGHT" name="Графический объект11" src="/images/news/letopis&#37;20magazina&#37;20120_mini.gif" /></a></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;"></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;">             <dl>                 <dt><b>Премия &laquo;Дядюшка Библио-Глобус&raquo;</b></dt><dt>                 Диплом за самый актуальный ассортимент для деловых людей</dt><dt>                 Благодарность за участие в создании юбилейной книги &laquo;Летопись                 магазина №120 &laquo;Книжный мир&raquo;- &laquo;Библио-Глобус&raquo;.</dt></dl>         </td>     </tr>
         
        <tr>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;">             <a onclick="javascript:window.open('/images/nagradi/04s.jpg','big','top=15, left=20, menubar=0, toolbar=0, location=0, directories=0, status=0, scrollbars=0, resizable=1, width=300, height=450');" href="javascript://"><img border="0" align="RIGHT" name="Графический объект11" src="/images/nagradi/04s.jpg" /></a></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;"></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;">             <dl>                 <dt><b>Кадровый менеджмент</b></dt><dt>                 Диплом за участие в выставке</dt></dl>         </td>     </tr>
         
        <tr>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;">              
            <p><u><b>Год 2003 </b></u>         </p>
           </td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;"></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;"></td>     </tr>
         
        <tr>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;">             <a onclick="javascript:window.open('/images/news/obrazovanie&#37;20i&#37;20kariera&#37;202003.gif','big','top=15, left=20, menubar=0, toolbar=0, location=0, directories=0, status=0, scrollbars=0, resizable=1, width=300, height=450');" href="javascript://"><img border="0" align="RIGHT" name="Графический объект11" src="/images/news/obrazovanie&#37;20i&#37;20kariera&#37;202003_mini.gif" /></a></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;"></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;">             <dl>                 <dt><b>Выставка Образование и карьера</b></dt><dt>                 Диплом Лауреата выставки Образование и карьера &mdash; шаг в                 будущее. Книга &mdash; 2003.                 </dt></dl>         </td>     </tr>
         
        <tr>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;">             <a onclick="javascript:window.open('/images/news/chelovek&#37;20knigi.gif','big','top=15, left=20, menubar=0, toolbar=0, location=0, directories=0, status=0, scrollbars=0, resizable=1, width=300, height=450');" href="javascript://"><img border="0" align="RIGHT" name="Графический объект11" src="/images/news/chelovek&#37;20knigi_mini.gif" /></a></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;"></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;">             <dl>                 <dt><b>Премия Человек Книги - 2003</b>                 </dt><dt>                 Диплом лауреата премии в номинации &laquo;Руководитель                 издательства&raquo; получил генеральный директор Алексей Ильин.</dt></dl>         </td>     </tr>
         
        <tr>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;">             <a onclick="javascript:window.open('/images/news/naufor_mini.gif','big','top=15, left=20, menubar=0, toolbar=0, location=0, directories=0, status=0, scrollbars=0, resizable=1, width=300, height=450');" href="javascript://"><img border="0" align="RIGHT" name="Графический объект11" src="/images/news/naufor_mini.gif" /></a></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;"></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;">             <dl>                 <dt><b>Национальная ассоциация участников фондового рынка</b></dt><dt>                 Диплом победителя национального конкурса &laquo;Элита фондового                 рынка 2002&raquo; в номинации &laquo;Лучшее деловое                 издательство&raquo;.</dt></dl>         </td>     </tr>
         
        <tr>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;">             <a onclick="javascript:window.open('/images/news/mezhdunar&#37;20assoc&#37;20alpinistov.gif','big','top=15, left=20, menubar=0, toolbar=0, location=0, directories=0, status=0, scrollbars=0, resizable=1, width=300, height=450');" href="javascript://"><img border="0" align="RIGHT" name="Графический объект11" src="/images/news/mezhdunar&#37;20assoc&#37;20alpinistov_mini.gif" /></a></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;"></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;">             <dl>                 <dt><b>Международная ассоциация профессиональных Альпинистов</b></dt><dt>                 Почетная грамота за самое стремительное покорение вершин книжного                 рынка.</dt></dl>         </td>     </tr>
         
        <tr>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;"></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;"></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;">             <dl>                 <dt><b>&laquo;Книга Года&raquo; </b>ежегодный конкурс издателей                 России</dt><dt>                 Дипломом оргкомитета 16 московской международной книжной                 выставки-ярмарки и министерство Российской Федерации по делам                 печати, телерадиовещания и средств массовых коммуникаций в                 номинации &laquo;Россия деловая&raquo; награждают издательство за                 издание книги М.А.Иванова и                 </dt><dt>                 Д.М.Шустермана &laquo;Организация как ваш инструмент&raquo;(Российский                 менталитет и практика бизнеса).</dt></dl>         </td>     </tr>
         
        <tr>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;"></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;"></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;">             <dl>                 <dt><span lang="en-US"><b>XVI </b></span><span lang="ru-RU"><b>московская                 международная книжная ярмарка, Москва</b></span></dt><dt>                 диплом за лучшее оформление книги Кузнецов К.В. &laquo;Настольная                 книга поставщика и закупщика: торги, конкурсы, тендеры&raquo;.</dt></dl>         </td>     </tr>
         
        <tr>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;">             <a onclick="javascript:window.open('" href="javascript://"><img border="0" align="RIGHT" name="Графический объект11" src="/images/nagradi/13s.jpg" /></a></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;"></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;">             <dl>                 <dt><b>XVI московская международная книжная ярмарка, Москва<span lang="en-US">.</span>                 Ежегодный конкурс издателей России &laquo;Книга года&raquo;</b></dt><dt>                 Диплом оргкомитета за издание книги М.А.Иванова и Д.М.Шустермана                 &laquo;Организация как ваш инструмент&raquo; (Российский                 менталитет и практика бизнеса) в номинации &laquo;Россия                 деловая&raquo;.</dt></dl>         </td>     </tr>
         
        <tr>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;"></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;"></td>         <td style="-moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; -moz-border-image: none;"></td>     </tr>
       </tbody>
     </table>
</div>